name: Release and Tag Muxi

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-and-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Run tests
      run: go test ./...

    - name: Get last tag
      id: get_last_tag
      run: |
        git fetch --tags
        TAG=$(git tag --list 'v*.*.0' --sort=-v:refname | head -n 1)
        if [ -z "$TAG" ]; then
          X=0
          Y=0
        else
          X=$(echo $TAG | sed -E 's/v([0-9]+)\.([0-9]+)\.0/\1/')
          Y=$(echo $TAG | sed -E 's/v([0-9]+)\.([0-9]+)\.0/\2/')
        fi
        Y=$((Y+1))
        NEXT_TAG="v${X}.${Y}.0"
        echo "NEXT_TAG=$NEXT_TAG" >> $GITHUB_ENV

    - name: Create and push tag
      env:
        NEXT_TAG: ${{ env.NEXT_TAG }}
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git tag "$NEXT_TAG"
        git push origin "$NEXT_TAG"
